# Generated by Django 4.1 on 2022-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('stock', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
